### ISSUE TITLE
Taxonomies ignoring uglyurls=true

### ISSUE THREAD

**Issue by abcfy2** [vividvilla/ezhil#4]
Seems that this theme does not support `uglyurls=true` option: https://gohugo.io/content-management/urls/#ugly-urls

**Comment by vividvilla** [comment]
This is supported and theme doesn't have to do anything special to implement this. Only change from your side is to configure nav links properly. Here is an example for sample site 

```toml
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts.html"
weight = 2

[[menu.main]]
name = "About"
url = "/about.html"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags.html"
weight = 4
```

Please reopen the issue it doesn't solve your issue.
